Taku/update ccloud grafana
confluentinc/jmx-monitoring-stacks pull request #125
Opened 2023-09-27 03:01 UTC by tsuz

| Item | Changes |
|--|--|
| Write on Topics | Change from Graph widget to Stats (since graph exists below and total ingress/sec doesn't exist) |
| Read on Topics | Change from Graph widget to Stats (since graph exists below and total egress/sec doesn't exist)  |
| Request (rate) | Change title to `Request Count (rate)` from `Request (rate)` |

**Before**
![Screenshot 2023-09-27 at 11 13 24](https://github.com/confluentinc/jmx-monitoring-stacks/assets/6927131/d6f9135b-e283-4f5a-8ab5-7019936b0205)

**After**

![Screenshot 2023-09-27 at 11 27 53](https://github.com/confluentinc/jmx-monitoring-stacks/assets/6927131/23148f28-070e-4beb-8cef-7deff0f70573)

2023-09-28 18:38 UTC, hifly81 commented on ccloud-prometheus-grafana/assets/grafana/provisioning/dashboards/ccloud.json
> +  "weekStart": ""
@tsuz is "weekStart" key required here?

2023-10-03 08:18 UTC, OoRobFuoO requested changes
Please verify and confirm the grafana dashboard will also work for Grafana 8.1?

2023-10-23 11:12 UTC, tsuz commented on ccloud-prometheus-grafana/assets/grafana/provisioning/dashboards/ccloud.json
> +      "pluginVersion": "10.1.2",
Reverted back to 8.1.3. Tested with that version also, thanks.

2023-10-23 11:12 UTC, tsuz commented on ccloud-prometheus-grafana/assets/grafana/provisioning/dashboards/ccloud.json
> +  "weekStart": ""
Removed it.

2023-10-23 11:41 UTC, hifly81 approved these changes
LGTM!

2023-10-24 06:55 UTC, hifly81 commented
@tsuz any ideas why license/cla is missing?

2023-10-25 00:53 UTC, tsuz commented
@hifly81 Ok, fixed the CLA issue. My git command line had different email config to my primary email.

2023-10-25 06:48 UTC, hifly81 commented
> @hifly81 Ok, fixed the CLA issue. My git command line had different email config to my primary email.

waiting the approval by
@OoRobFuoO

2023-11-16 18:17 UTC, merged