ADD: dev-toolkit
confluentinc/jmx-monitoring-stacks pull request #146
Opened 2023-10-25 12:55 UTC by ram-pi

WIP for a dev-toolkit. The purpose is to have a small new dev environment in which to test new grafana dashboards.

2023-10-26 16:35 UTC, hifly81 requested changes

2023-10-26 16:35 UTC, hifly81 commented on .gitignore
pls solve the conflicts

2023-10-26 16:35 UTC, hifly81 commented on README.md
pls solve the conflicts

2023-10-30 08:46 UTC, tsuz commented
@hifly81 @ram-pi  Will review when moved from `Draft` to `Ready for Review`.

2023-10-31 14:41 UTC, hifly81 approved these changes

2023-10-31 14:42 UTC, merged